// server/utils/generatePDF.js

const PDFDocument = require('pdfkit')

const generateAssetRegisterPDF = (caseData, assets, res) => {
  const doc = new PDFDocument({ margin: 50 })

  res.setHeader('Content-Type', 'application/pdf')
  res.setHeader('Content-Disposition', `attachment; filename=asset-register-${caseData._id}.pdf`)

  doc.pipe(res)

  doc.fontSize(18).text('Anvaya — Asset Register Summary', { align: 'center' })
  doc.moveDown()

  doc.fontSize(11)
  doc.text(`Case ID: ${caseData._id}`)
  doc.text(`Nominee Name: ${caseData.nomineeName}`)
  doc.text(`Deceased Name: ${caseData.deceasedName}`)
  doc.text(`Generated On: ${new Date().toLocaleDateString('en-IN')}`)
  doc.moveDown()

  doc.fontSize(14).text('Assets', { underline: true })
  doc.moveDown(0.5)

  if (!assets || assets.length === 0) {
    doc.fontSize(11).text('No assets recorded for this case.')
  } else {
    assets.forEach((asset, index) => {
      doc.fontSize(12).text(`${index + 1}. ${asset.type}`, { continued: false })
      doc.fontSize(10)
      doc.text(`   Institution: ${asset.institution || 'N/A'}`)
      doc.text(`   Account/Reference No: ${asset.accountNumber || 'N/A'}`)
      doc.text(`   Value: ${asset.value != null ? `₹${asset.value}` : 'N/A'}`)
      doc.text(`   Status: ${asset.status || 'Pending'}`)
      doc.moveDown(0.5)
    })
  }

  doc.moveDown()
  doc.fontSize(9).fillColor('gray').text('Generated by Anvaya — Built for the living, not the dead.', { align: 'center' })

  doc.end()
}

module.exports = { generateAssetRegisterPDF }